name: Deploy Custom Chatbot API

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install dependencies
      working-directory: custom-api-chatbot
      run: npm install

    - name: Archive Dockerfile
      run: echo "Docker build can be added here if required"

    # - name: Deploy to EC2 (optional)
    #   run: echo "You can SSH and deploy from here"
