name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.8.0
      with:
        ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

    - name: Deploy to EC2
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
          cd ~/ai-chatbot-complete/custom-api-chatbot

          echo "🟡 Pulling latest changes from GitHub..."
          git fetch --all
          git reset --hard origin/main

          echo "🟠 Stopping and removing existing container if any..."
          docker stop chatbot-container || true
          docker rm chatbot-container || true

          echo "🟢 Building Docker image..."
          docker build -t chatbot-api .

          echo "🔵 Running new container..."
          docker run -d -p 3000:3000 --name chatbot-container chatbot-api

          echo "✅ Deployment finished."
        EOF
